name: Build and Push Docker Image Without Buildx

on:
  push:
    branches:
      - main
      - login-gcr.io # @note: use any development branch you would like

jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      # Checkout code
      - uses: actions/checkout@v4

      # Authenticate with GCP using workload identity provider
      - uses: 'google-github-actions/auth@v2'
        id: auth
        name: Authenticate to GCP
        with:
          project_id: 'elegant-weaver-435322-v8' # Update with your project ID
          workload_identity_provider: 'projects/186852006700/locations/global/workloadIdentityPools/github/providers/my-repo' 

      # Configure Docker to use Google Artifact Registry
      - name: gcloud Configure Docker
        run: |
          gcloud auth configure-docker us-east1-docker.pkg.dev

      # Build and push the Docker image using regular Docker commands
      - name: Build and Push Without Buildx
        run: |
          docker build -t us-east1-docker.pkg.dev/elegant-weaver-435322-v8/artifact-repo/haydenw59/cs1660-assignment3 .
          docker push us-east1-docker.pkg.dev/elegant-weaver-435322-v8/artifact-repo/haydenw59/cs1660-assignment3




